id: P000342
initial_creation_type: ocr
created_at: 14/03/2020
last_modified_at: 2021-12-16 15:34:58.188025
source_metadata:
  id: bdr:W1KG21760
  title: བོད་ཀྱི་སྐར་རྩིས་རིག་པའི་རྣམ་བཞག
  author: ''
  volumes:
    18d9bb1c466341bd9e25ae719db6d25d:
      image_group_id: I1KG21870
      title: Volume 1 of bod kyi skar rtsis rig pa'i rnam bzhag
      volume_number: 1
      total_pages: 518
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
